import { bootstrapApplication } from '@angular/platform-browser';
import { addIcons } from 'ionicons';
import {
    appsOutline,
    arrowBackOutline,
    book,
    checkmark,
    cloud,
    construct,
    contrastOutline,
    documentTextOutline,
    download,
    eyeOutline,
    globe,
    help,
    home,
    information,
    library,
    list,
    lockClosed,
    logoFirebase,
    logoGithub,
    logoGooglePlaystore,
    mail,
    person,
    phonePortrait,
    rocket,
    searchOutline,
    sunny,
    trashOutline,
    warning,
    cloudyOutline,
    cloudCircleOutline,
    informationCircle,
    closeOutline,
    globeOutline,
    chevronBackOutline,
    personOutline,
    mailOutline,
    locationOutline,
    chevronUpOutline,
    chevronDownOutline,
    listOutline,
    downloadOutline,
    alertCircleOutline,
    arrowBack,
    settingsOutline,
    helpOutline,
} from 'ionicons/icons';

import { appConfig } from './app/app.config';
import { AppComponent } from './app/app.component';

// Register Ionicons used in the application
addIcons({
  'alert-circle-outline': alertCircleOutline,
  'apps-outline': appsOutline,
  'arrow-back': arrowBack,
  'arrow-back-outline': arrowBackOutline,
  book: book,
  checkmark: checkmark,
  'chevron-back-outline': chevronBackOutline,
  'chevron-down-outline': chevronDownOutline,
  'chevron-up-outline': chevronUpOutline,
  'cloud-download': cloud,
  'cloud-upload-outline': cloud,
  'cloud-circle-outline': cloudCircleOutline,
  'cloudy-outline': cloudyOutline,
  'close-outline': closeOutline,
  construct: construct,
  'contrast-outline': contrastOutline,
  'document-text': documentTextOutline,
  'document-text-outline': documentTextOutline,
  download: download,
  'download-outline': downloadOutline,
  'eye-outline': eyeOutline,
  globe: globe,
  'globe-outline': globeOutline,
  'help-outline': helpOutline,
  help: help,
  home: home,
  information: information,
  'information-circle': informationCircle,
  library: library,
  list: list,
  'list-outline': listOutline,
  'location-outline': locationOutline,
  'lock-closed': lockClosed,
  'logo-firebase': logoFirebase,
  'logo-github': logoGithub,
  'logo-google-playstore': logoGooglePlaystore,
  mail: mail,
  'mail-outline': mailOutline,
  person: person,
  'person-outline': personOutline,
  'phone-portrait': phonePortrait,
  rocket: rocket,
  'search-outline': searchOutline,
  'settings-outline': settingsOutline,
  sunny: sunny,
  'trash-outline': trashOutline,
  warning: warning,
});

bootstrapApplication(AppComponent, appConfig);
